site_name: "Я – Дата Инженер"
repo_name: Roadmappers.ru
repo_url: https://github.com/halltape/HalltapeRoadmapDE
site_url: https://roadmappers.ru
copyright: MIT

# Явное, лаконичное меню
nav:
  - В начало: README.md
  - BootCamp: /HalltapeRoadmapDE/#bootcamp-data-engineer
  - Деньги: /HalltapeRoadmapDE/#0
  - Кто такой DE: /HalltapeRoadmapDE/#1
  - Курсы: /HalltapeRoadmapDE/#2
  - Git: /HalltapeRoadmapDE/#3-github-git
  - Linux/Terminal: /HalltapeRoadmapDE/#4-linux-terminal
  - DWH: /HalltapeRoadmapDE/#5-data-warehouse-data-lake-data-lakehouse
  - NF: /HalltapeRoadmapDE/#6
  - Модели Данных: /HalltapeRoadmapDE/#7
  - DataVault: /HalltapeRoadmapDE/#8-data-vault-hub-satellite-link
  - Индексы: /HalltapeRoadmapDE/#9
  - Docker: /HalltapeRoadmapDE/#10-docker
  - Hadoop: /HalltapeRoadmapDE/#11-hadoop
  - Airflow: /HalltapeRoadmapDE/#12-airflow
  - Greenplum: /HalltapeRoadmapDE/#13-greenplum
  - Clickhosue: /HalltapeRoadmapDE/#14-clickhouse
  - Spark: /HalltapeRoadmapDE/#15-spark
  - dbt: /HalltapeRoadmapDE/#16-dbt-data-build-tool
  - Kafka: /HalltapeRoadmapDE/#17-apache-kafka
  - Pet Project: /HalltapeRoadmapDE/#18-pet-project
  - Собесы: /HalltapeRoadmapDE/#19-c
  - Резюме и Работа: /HalltapeRoadmapDE/#20
  - Кейсы: /HalltapeRoadmapDE/#21
  - Полезные ссылки: /HalltapeRoadmapDE/#22

theme:
  name: material
  palette:
    scheme: slate  # тёмная тема (можно убрать для светлой)
  font:
    text: Roboto
    code: Fira Mono
  code:
    highlight_theme: material
  logo: _frontend/images/logo_v2.svg

# Только свой CSS
extra_css:
  - _frontend/css/custom.css

extra_javascript:
  - _frontend/js/toc-home.js
  - _frontend/js/scroll-to-top.js


markdown_extensions:
  - admonition
  - tables
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true       # номера строк якорями
      line_spans: __span          # для подсветки отдельных строк
      pygments_lang_class: true   # классы языка для тем
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - tables
  - footnotes